language: python
python:
  - "3.5"
env:
  - DB_URL=mysql://travis:@localhost:3306/easystatus

before_script:
  - mysql -e 'create database easystatus;'

instale: "pip install -r requirements.txt"
script: "make test"
